# SNMP Exporter configuration for FortiNet devices
auths:
  public_v2:
    community: public
    security_level: noAuthNoPriv
    auth_protocol: MD5
    priv_protocol: DES
    version: 2

modules:
  # FortiNet FortiGate SNMP monitoring
  fortigate:
    walk:
      - 1.3.6.1.2.1.1.3.0     # sysUpTime
      - 1.3.6.1.2.1.1.5.0     # sysName  
      - 1.3.6.1.2.1.2.2.1.2   # ifDescr
      - 1.3.6.1.2.1.2.2.1.8   # ifOperStatus
      - 1.3.6.1.2.1.2.2.1.10  # ifInOctets
      - 1.3.6.1.2.1.2.2.1.16  # ifOutOctets
      - 1.3.6.1.4.1.12356.101.4.1.3.0  # fgSysCpuUsage
      - 1.3.6.1.4.1.12356.101.4.1.4.0  # fgSysMemUsage
      - 1.3.6.1.4.1.12356.101.4.1.8.0  # fgSysSesCount
    auth:
      community: public

  # Generic network device  
  if_mib:
    walk:
      - 1.3.6.1.2.1.2.2.1.2   # ifDescr
      - 1.3.6.1.2.1.2.2.1.8   # ifOperStatus  
      - 1.3.6.1.2.1.2.2.1.10  # ifInOctets
      - 1.3.6.1.2.1.2.2.1.16  # ifOutOctets
    auth:
      community: public
