apiVersion: 1

datasources:
  # Prometheus - Main metrics data source
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true
    uid: prometheus-uid
    jsonData:
      timeInterval: "15s"
      queryTimeout: "60s"
      httpMethod: "POST"
    version: 1

  # Loki - Log aggregation data source  
  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    editable: true
    uid: loki-uid
    jsonData:
      maxLines: 1000
      timeout: "60s"
    version: 1
